import os
import shutil
import logging

def clean_pipeline_data():
    """
    Cleans all data, datasets, logs, and caches generated by the pipeline.
    """
    print("============================================================")
    print("               PIPELINE CLEANUP SCRIPT")
    print("============================================================")
    
    # Directories to delete completely
    dirs_to_delete = [
        "YOLO_dataset",
        "dataset",
        ".cache",
    ]
    
    # Files to delete
    files_to_delete = [
        "pipeline.log"
    ]
    


    print("\n[1] Deleting generated directories...")
    for d in dirs_to_delete:
        if os.path.exists(d):
            print(f"  - Removing directory: {d}")
            try:
                shutil.rmtree(d)
            except Exception as e:
                print(f"    Error removing {d}: {e}")
        else:
            print(f"  - Directory {d} does not exist. Skipping.")

    print("\n[2] Deleting log files...")
    for f in files_to_delete:
        if os.path.exists(f):
            print(f"  - Removing file: {f}")
            try:
                os.remove(f)
            except Exception as e:
                print(f"    Error removing {f}: {e}")
        else:
            print(f"  - File {f} does not exist. Skipping.")


        
    print("\nCleanup complete! The workspace is ready for a fresh pipeline run.")
    print("============================================================\n")

if __name__ == "__main__":
    confirm = input("WARNING: This will delete all generated images, labels, logs, and cached data.\nAre you sure you want to proceed? (y/n): ").strip().lower()
    if confirm == 'y':
        clean_pipeline_data()
    else:
        print("Cleanup aborted.")
