from enum import Enum

class BuildingRetrievalState(Enum):
    BUILDINGS_FOUND = "BUILDINGS_FOUND"
    NO_BUILDINGS_FOUND = "NO_BUILDINGS_FOUND"
    SOURCE_COVERAGE_UNAVAILABLE = "SOURCE_COVERAGE_UNAVAILABLE"
    SOURCE_QUERY_FAILED = "SOURCE_QUERY_FAILED"
    SOURCE_ACCESS_FAILED = "SOURCE_ACCESS_FAILED"
    INVALID_GEOMETRY = "INVALID_GEOMETRY"

class CoverageStatus(Enum):
    FULLY_WITHIN_IMAGE = "FULLY_WITHIN_IMAGE"
    PARTIALLY_WITHIN_IMAGE = "PARTIALLY_WITHIN_IMAGE"

class PipelineState(Enum):
    INVALID_COORDINATES = "INVALID_COORDINATES"
    NO_FREE_IMAGERY_FOUND = "NO_FREE_IMAGERY_FOUND"
    IMAGE_DOWNLOAD_FAILED = "IMAGE_DOWNLOAD_FAILED"
    IMAGE_METADATA_INVALID = "IMAGE_METADATA_INVALID"
    IMAGE_FOOTPRINT_UNAVAILABLE = "IMAGE_FOOTPRINT_UNAVAILABLE"
    BUILDING_SOURCE_COVERAGE_UNAVAILABLE = "BUILDING_SOURCE_COVERAGE_UNAVAILABLE"
    BUILDING_SOURCE_QUERY_FAILED = "BUILDING_SOURCE_QUERY_FAILED"
    NO_BUILDINGS_IN_IMAGE = "NO_BUILDINGS_IN_IMAGE"
    INVALID_BUILDING_GEOMETRY = "INVALID_BUILDING_GEOMETRY"
    OUTPUT_GENERATION_FAILED = "OUTPUT_GENERATION_FAILED"
    SUCCESS = "SUCCESS"

class VisualStatus(Enum):
    VERIFIED_VISIBLE_BUILDING = "VERIFIED_VISIBLE_BUILDING"
    PROBABLE_BUILDING = "PROBABLE_BUILDING"
    UNRESOLVED = "UNRESOLVED"
    REJECTED_NON_BUILDING = "REJECTED_NON_BUILDING"
